### ISSUE TITLE
Info: Upcoming release of `openmmforcefields` with temporary removal of GAFF support

### ISSUE THREAD

**Issue by mattwthompson** [asapdiscovery/asapdiscovery#1036]
Just a heads up - 

For a fairly messy set of reasons, we're soon making a release of `openmmforcefields` that drops `GAFFTemplateGenerator` and plan to follow it up with another release that adds it back in a few weeks or (small number of) months. Non-GAFF (i.e. SMIRNOFF) usage shouldn't be affected. Context is [here](https://github.com/openmm/openmmforcefields/issues/280#issuecomment-2093024734) and from some of the linked issues.

We found that this [package is a downstream user](https://gist.github.com/mattwthompson/08f7621c658d7d6ceefee46651e210aa), but [here](https://github.com/choderalab/asapdiscovery/blob/387857c35b91c98038169d9c6ecd72bdfe33d51d/asapdiscovery-simulation/asapdiscovery/simulation/simulate.py#L336-L343) being the only place I see it called. Since you're not using GAFF, I expect this code won't be affected.

If there are issues that crop up please get in touch with myself or @mikemhenry

**Comment by hmacdope** [comment]
Thanks @mattwthompson, much appreciated. :)
