### ISSUE TITLE
Trigger ML suite training periodically on iris

### ISSUE THREAD

**Issue by hmacdope** [asapdiscovery/asapdiscovery#1086]
We need to trigger training for every endpoint on `iris` using a job array at a **specific schedule** 

We can use a cron job for this (maybe?) but we need to talk to HPC.

**Comment by hmacdope** [comment]
@mikemhenry if you have some spare cycles would you be able to hit this one?

**Comment by mikemhenry** [comment]
Do we need this to run a self-hosted runner for github to pick up or do we just need a job to run locally and email us if it fails?

**Comment by hmacdope** [comment]
We just need a job to run locally on a schedule.

**Comment by hmacdope** [comment]
Done with a cronjob.
