### ISSUE TITLE
Problems with FF for RosettaFold generated proteins

### ISSUE THREAD

**Issue by mariacm12** [asapdiscovery/asapdiscovery#1095]
In the post-docking MD pipeline (_e.g._, small-scale docking), I am having problems running docking and then MD simulations for proteins folded using RosettaFold All-atom. 
The docking runs just fine, but the job fails at the moment of preparation of the MD simulation, with the message:

`Did not recognize residue SER; did you forget to call .add_molecules() to add it?`

If a previous protein-preparation with Maestro is performed on the folded structure, the MD runs normally. 

May be solved by adding an extra protein-prep step with PDBFixer.

**Comment by apayne97** [comment]
Can you send the pdb file that is failing?

**Comment by mariacm12** [comment]
Here's the pdb file: 
[mers_apo_protein_rf.pdb.gz](https://github.com/user-attachments/files/15891605/mers_apo_protein_rf.pdb.gz)

I think the problem is with the protein not being "capped" by the right residue, but I don't know how to fix it with PDBFixer.
I tried the following:

```
fixer = PDBFixer(str(pdb_file))

fixer.findMissingResidues()
fixer.findNonstandardResidues()
fixer.replaceNonstandardResidues()
fixer.removeHeterogens(True)
fixer.findMissingAtoms()
fixer.addMissingAtoms()
fixer.addMissingHydrogens(7.4)
```
