### ISSUE TITLE
Error retrieving E3NN scores

### ISSUE THREAD

**Issue by mariacm12** [asapdiscovery/asapdiscovery#1122]
I'm getting this error when requesting ML scoring with E3NN with the `large-scale` docking pipeline:

`2024-07-01 16:11:06,118 | urllib3.connectionpool | DEBUG | connectionpool.py | _make_request | [https://asap-discovery-ml-weights.s3.amazonaws.com:443](https://asap-discovery-ml-weights.s3.amazonaws.com/) "GET /production/e3nn/asapdiscovery-SARS-CoV-2-Mpro-e3nn-2024.02.06.th HTTP/11" 403 None`

While the other two models are working fine (GAT and SchNet).

**Comment by hmacdope** [comment]
Ah this is an issue to do with bucket migration to non-public source tagging @dotsdl. I will chase this up ASAP. No code issue on your side.
