### ISSUE TITLE
The current saving format of asapdiscovery-simulation needs to be more general

### ISSUE THREAD

**Issue by mariacm12** [asapdiscovery/asapdiscovery#1153]
I want to implement a minimization and re-docking step for the `ligand-transfer-docking` pipeline, but the current `outpath` format wouldn't allow for me to do a second docking step. Specifically, right now the output format looks like `out_dir/input.unique_name/minimized.pdb`, but I would need to save the files in a single "raw" directory to be able to read them back into the workflow. 

Can we implement an option to save the outputs in a raw directory?

**Comment by hmacdope** [comment]
So to clarify you would like an option to get `out_dir/unique_name1.pdb`,  `out_dir/unique_name_2.pdb` etc etc?

**Comment by mariacm12** [comment]
Yes! With all the files on the same directory.

**Comment by ijpulidos** [comment]
My 2 cents, doesn't it make more sense for the `ligand_transfer-docking` pipeline to accept a path wherever the files live instead? I'm not really familiar with the pipeline so I may be way off here.

**Comment by mariacm12** [comment]
So the reason I want to have all in the same directory is because the type of target/complexes inputs that the general docking cli takes is either a pdb file, a folder of pdb files or a folder of fragalysis data. I thought it would be easier to use the existing input formats rather than making a new one? But maybe another input type would be easier to implement? @hmacdope
