### ISSUE TITLE
`ns2b3` splitting is wonky 

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#1179]
in our pipelines, OE treats chain A (the shorter one) as a ligand when an apo structure is fed in. This affects many different pipelines currently, e.g. `asap-cli simulation vanilla-md` and fitness views.

**Comment by ijpulidos** [comment]
Is this because of the size of the chain or just that we cannot handle multiple chains in the structures?

**Comment by JenkeScheen** [comment]
Both I think - we (OE) handle homodimers like Mpro just fine, but NS2B3 is a heterodimer. The second chain is also fairly small (only 40-50 residues) so OE occasionally even treats it like a ligand.
