### ISSUE TITLE
`alchemy gather` seems to be hanging / taking forever on a large download

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#1180]
for a network with 1516 tasks (confidential key), it's taken a few hours now and it looks like it's hanging at task 1449. Is there a chance it's loading too much into memory recursively up to a point where it can't fill up anymore? 
![image](https://github.com/user-attachments/assets/d99c11fe-7aac-41fd-aed9-0aca1ce6e826)

**Comment by JenkeScheen** [comment]
perhaps @dotsdl you might have ideas here? see here on how we `gather`: https://github.com/asapdiscovery/asapdiscovery/blob/main/asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py#L294

**Comment by dotsdl** [comment]
Thanks for this @JenkeScheen. I've worked to reproduce this on my local workstation. Raw notes from this exercise:

Observations from running `get_network_results` on `vulkan`.
- about 9 minutes in
	- memory and swap space fill, system load climbs to beyond 8 (full load on this host), then drops down again
	- load on server appears fine; memory is climbing but holds steady just below 50%
	- only downloaded 366 out of 1516 `Transformation` results
- about 14 minutes in
	- memory full, swap at 73%
	- system load holding at 7.54
	- 428 results retrieved
- 17 minutes in
	- memory full, swap at 87.6%
	- system load still stable
	- 470 results retrieved
- 21 minutes in
	- all memory and swap exhausted
	- 496 results retrieved
- 23 minutes in: system unresponsive

Hypotheses:
- perhaps the `ProtocolDAGResult`s produced by `openfe` 1.0 are quite a bit larger on average than those produced pre-1.0?
- are the `ProtocolDAG`s produced by the `RelativeHybridTopologyProtocol` more complex?
	- we have yet to switch to `KeyedChain` storage of `ProtocolDAGResult`s
- are the individual processes in the `ProcessPoolExecutor` holding on to deserialized objects in memory, not garbage collecting?

Temporary workaround recommendations:
- could use `get_transformation_results` in combination with `get_network_transformation`s in a `for` loop to get all the results without using a `ProcessPoolExecutor`
	- will be much slower, but *might* sidestep memory issues

**Comment by dotsdl** [comment]
I'll follow up on the hypotheses and see if we can't identify what's different about these results vs. ones produced for `AlchemicalNetwork`s previously, including pre `gufe`+`openfe` 1.0. This is the first time I've seen behavior this bad from `get_network_results`, so I suspect it may have something to do with changes related to that.

**Comment by hmacdope** [comment]
I managed to pull this down, but took a 250GB swap file for a resulting 11Mb file, so something is a bit off.

**Comment by dotsdl** [comment]
Oh dear, yeah that's not good.

All of these `ProtocolDAGResult`s now feature `structural_analysis` outputs, which gives RMSDs for various components over time, for every replica. This looks like it may be the largest new addition, and might be causing the ballooning memory usage.

Will investigate further if this is indeed the cause, and then consider how we might address it either in `alchemiscale` or in the OpenFE `RelativeHybridToplogyProtocol` itself.

@ialibay any insights on this?

**Comment by IAlibay** [comment]
I'm pretty sure structural analysis is the problem, we've been seeing similar problems with the industry benchmarks where the json files started getting really big. 

I have a general idea of how to fix this (just don't store the rmsd matrix is a good start), but I've not had time to fix / do a release yet. We should talk and work out a plan.

**Comment by dotsdl** [comment]
Ah good, thank you for this @ialibay! I'll raise a corresponding issue on `openfe` and we can continue discussion there on possible approaches.

**Comment by dotsdl** [comment]
See OpenFreeEnergy/openfe#926 for follow-up discussion on possible solutions to this issue.

**Comment by jthorton** [comment]
Fixed in https://github.com/OpenFreeEnergy/openfe/pull/937 just wanting on a new release for production!

**Comment by dotsdl** [comment]
Working to deploy the new `openfe` release to alchemiscale.org prod now!

**Comment by JenkeScheen** [comment]
fixed with update to OpenFE 1.1.0 and alchemiscale 0.5.1
