### ISSUE TITLE
`asap-alchemy stop -nk` only stops `waiting` tasks, doesn't cancel `running` tasks

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#1196]
this call should be adjusted to first set all `running` tasks to `waiting`, then un-action all `waiting` tasks.

**Comment by JenkeScheen** [comment]
should just be a matter of running
```
asc.set_tasks_status(asc.get_network_tasks(an_sk), status="waiting")
```
but not sure if this actually clears the task from the workers server-side. @dotsdl can you advise?

**Comment by dotsdl** [comment]
See this issue for how we might resolve this in `alchemiscale`: https://github.com/openforcefield/alchemiscale/issues/301
