### ISSUE TITLE
cdd api not importing David Minh's pIC50 

### ISSUE THREAD

**Issue by mariacm12** [asapdiscovery/asapdiscovery#1200]
I'm trying to import the pIC50s calculated by David Mihn's method which are available as `'Minh_Protease_MERS_Mpro_pIC50 (calc)'`, in the `'MERS-CoV-MPro_fluorescence-dose-response_weizmann'` protocol using `asapdiscovery.data.services.cdd.cdd_api`. 

However, although the parameter is listed in `protocol['readout_definitions']`, when I do 

`readout_data = cdd.get_readout_rows(protocol=protocols[0]["id"], types=["batch_run_aggregate_row"])`  

none of the resulting entries have the property I'm looking for (although I can see the number on the CDD!). Ideally I would like to import this number with the `cdd_api.get_ic50_data()` function whenever it's available.

**Comment by hmacdope** [comment]
@mariacm12 the following should work. you will also need to set the relevant environment variables `CDD_API_KEY` and `CDD_VAULT_NUMBER`

```python
from asapdiscovery.data.services.cdd.cdd_api import CDDAPI
from asapdiscovery.data.services.services_config import CDDSettings

settings = CDDSettings()
api = CDDAPI.from_settings(settings)
data_df = api.get_readout("MERS-CoV-MPro_fluorescence-dose-response_weizmann", 'Minh_Protease_MERS_Mpro_pIC50 (calc)')
```

Let me know how that goes!

**Comment by mariacm12** [comment]
Thanks! It doesn't work though :(
I'm using the function `get_readout_rows`:

`data_df = api.get_readout_rows("MERS-CoV-MPro_fluorescence-dose-response_weizmann", 'Minh_Protease_MERS_Mpro_pIC50 (calc)')`

**Comment by hmacdope** [comment]
FIxed
