### ISSUE TITLE
`ASAP-Alchemy`: Box shape

### ISSUE THREAD

**Issue by jthorton** [asapdiscovery/asapdiscovery#1207]
In OpenFE main we can now select non-cubic simulation boxes which should increase simulation speeds for FEC, we will need to change the default from `cubic` in our protocols once a new version of OpenFE is released. See [here](https://github.com/OpenFreeEnergy/openfe/blob/f4475bfe47fa53614cf22ba7e7662a6cf288ba4b/openfe/protocols/openmm_utils/omm_settings.py#L105-L161) for the new solvation settings.

**Comment by JenkeScheen** [comment]
octahedron will probably be best for default
