### ISSUE TITLE
something iffy with postera downloads

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#1213]
on `alchemy prep run -pm <molset>` no compounds are passing `Ligand` creation. I'm getting:
```
/Users/jenkescheen/asapdiscovery/asapdiscovery-data/asapdiscovery/data/services/postera/postera_factory.py:59: UserWarning: Failed to create ligand from smiles:
[confidential SMILES]
  warnings.warn(f"Failed to create ligand from smiles: {smiles}")
```
on everything. Downloading the molset and then running `alchemy prep run -l <molset.sdf>` works just fine.

**Comment by hmacdope** [comment]
@JenkeScheen is it a CXSmiles?

**Comment by hmacdope** [comment]
Current fix is mint a new API key, seems like something is off upstream.
