### ISSUE TITLE
adaptive sampling: double sampling time on edges with mapper scores > n

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#1227]
Find a threshold for edge scores and double sampling time above that.

**Comment by JenkeScheen** [comment]
sketch of how to do this:
- on `asap-alchemy plan`, expose an option to activate/inactivate adaptive sampling per edge (default should be _active_)
- for a given edge during setup, find sampling time in protocol: https://github.com/asapdiscovery/asapdiscovery/blob/main/asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py#L343
- if option is set to active, create a copy of the `protocol` and adjust it to have double the sampling time
- for each edge during setup, find the edge scoring and if it's below 0.5 set it up with the new protocol: https://github.com/asapdiscovery/asapdiscovery/blob/main/asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py#L362

We could do some exploration on whether 0.5 is a good threshold (or even expose it as an option) but in my experience 0.5 is a good enough approximation because it's heavily dependent on the ligand series and the atom mapper algorithm.

**Comment by jthorton** [comment]
Somewhat related to this we should also be changing the lambda windows and sampling time for transformations with net charge changes, I think we currently avoid these but it would be great to know they work!
