### ISSUE TITLE
When IC50 stderrors are very large pIC50 and IC50 values can be clipped to very large numbers.

### ISSUE THREAD

**Issue by hmacdope** [asapdiscovery/asapdiscovery#1234]
Using stderr based rounding for IC50s and pIC50s here: https://github.com/asapdiscovery/asapdiscovery/blob/main/asapdiscovery-data/asapdiscovery/data/util/utils.py#L951-L956

Can make values very large if stderrs are large. We should work on some kind of fix.

**Comment by hmacdope** [comment]
We will add an option to clip above a certain error cutoff and also a warning for large error values if not CC @kaminow

**Comment by hmacdope** [comment]
@kaminow can I leave this one to you?

**Comment by kaminow** [comment]
:saluting_face:
