### ISSUE TITLE
Make the project conda or pip installable

### ISSUE THREAD

**Issue by ijpulidos** [asapdiscovery/asapdiscovery#20]
Having this tool to be easily to install using pip or conda is desired if we want other folks to include it in bigger pipelines. For this purpose we might have to think about how to split the different functionalities into their own packages or projects and deploy them separately as needed.

**Comment by hmacdope** [comment]
Happy to help package :) I'll consider #98 blocking for now, let me know if that changes . 😸

**Comment by apayne97** [comment]
is this resolved? it is locally pip installable, right?

**Comment by kaminow** [comment]
it's not on `conda-forge` or `PyPi` yet though, which I think is the end goal

**Comment by ijpulidos** [comment]
If we don't plan to change the names of the packages anytime soon I think we are already in a place where we could think of making them conda installable. I think the issue with PyPI is making sure the ML libs/frameworks dependencies are actually the ones we want (modern cuda support, etc.).

**Comment by hmacdope** [comment]
For conda install we would need all deps to be conda-installable, pip is easier in that respect but also more complicated re things that @ijpulidos mentioned.

**Comment by hmacdope** [comment]
I think it is doable though.

**Comment by hmacdope** [comment]
Moving off 0.3.0 so we can release, but this is next cab off rank.

**Comment by hmacdope** [comment]
Done!
