### ISSUE TITLE
an option to make generated networks have redundancy, i.e. all ligand nodes should be in a cycle

### ISSUE THREAD

**Issue by dotsdl** [asapdiscovery/asapdiscovery#472]

**Comment by JenkeScheen** [comment]
happy to help out here, it'll be a matter of grabbing the edge scorings for whatever ligand network generator is being used, then adding the 'second-best' scored edge for each ligand.

**Comment by JenkeScheen** [comment]
might be better to implement this in OpenFE directly as they're aiming to extend their network types over the next few months. I'll submit a PR there, then we can just pull that functionality into `asap-alchemy`.

**Comment by dotsdl** [comment]
@JenkeScheen this sounds like a good plan! Yes, I think it makes sense to get this kind of functionality into the network planners themselves instead of us tacking it on from the outside.

**Comment by JenkeScheen** [comment]
implementing this here: https://github.com/OpenFreeEnergy/openfe/pull/559

**Comment by hmacdope** [comment]
This is fixed now to my knowledge, closing
