### ISSUE TITLE
Add in-memory end-to-end ML pipeline

### ISSUE THREAD

**Issue by kaminow** [asapdiscovery/asapdiscovery#752]
As a future example @kaminow and as part of #601 (or extension thereof) it would be good to be able to do the whole pipline in-memory if that makes sense? That way a notebook could be self contained etc and the ML pipeline will be more robust wrt FS and execution location etc.

_Originally posted by @hmacdope in https://github.com/choderalab/asapdiscovery/issues/575#issuecomment-1804967606_

**Comment by kaminow** [comment]
@hmacdope to clarify on this, did you mean add like a workflow class/function that does all of these steps? or something else?

**Comment by hmacdope** [comment]
More just can you run the ML end2end in a workbook without any intermediate files?

**Comment by kaminow** [comment]
ah gotcha. I think that should be doable with the code as-is, but I'll put together an example and add any code we need

**Comment by hmacdope** [comment]
Done
