### ISSUE TITLE
add MERS fitness data

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#755]
We need to add data from SI in https://www.biorxiv.org/content/10.1101/2023.12.04.569917v1.supplementary-material to MERS. Will need to wrangle table S2 into a format that is ingestible by Bloom et al's JSON generator, then we can easily add it to the fitness view workflows.

There's also talk of 'combining' this data with phylogenicity data that Bloom et al can extract (even though there are far fewer sequences logged compared to SARS-CoV-2 this data will still be useful for making design decisions). How exactly we're going to combine these two datasets is an open question - might just do an easy ensemble score or something.

**Comment by hmacdope** [comment]
Solved by @JenkeScheen choppa
