### ISSUE TITLE
ASAP-Alchemy: Support Non-equilibrium cycling

### ISSUE THREAD

**Issue by jthorton** [asapdiscovery/asapdiscovery#808]
FEFlow now supports [non-equilibrium cycling protocols](https://github.com/choderalab/feflow/blob/main/feflow/protocols/nonequilibrium_cycling.py) and it would be great to add support for this in asap-alchemy. We will probably need to rework the `FreeEnergyCalculationFactory` to work to support both the current equilibrium methods and this new protocol, this should also make it easier to support ATM and SepTop once implemented in FEFlow.

**Comment by hmacdope** [comment]
Duplicate of #1116
