### ISSUE TITLE
`asap-alchemy` find best crystal reference for a folder with PDB files

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#918]
a current bottleneck in the pipeline is finding a good crystal reference. Trawling the google drive is time-consuming mostly because there's no easy way of seeing the ligand's structure there.

we need to build some code using @apayne97's fragalysis code (that matches by MCS) to do this automatedly instead; for now finding the reference in a folder should be good enough (can just keep it local and download periodically from google drive).

**Comment by jthorton** [comment]
Good idea, I guess we would need to find the crystal reference that has the largest MCS match to all of the ligands we want to run on assuming we are using a single reference for the whole set.

**Comment by JenkeScheen** [comment]
yep, code should be pretty much there already I think. I'll make a first pass to see where it gets us

**Comment by hmacdope** [comment]
This should help yall get started, picks the best complex for each ligand.

```python 
from asapdiscovery.data.operators.selectors.mcs_selector import MCSSelector
from asapdiscovery.data.readers.structure_dir import StructureDirFactory

ligands = ...
structure_factory = StructureDirFactory.from_dir(self.structure_dir)
complexes = structure_factory.load( )
selector = MCSSelector()
    pairs = selector.select(
        ligands,
        complexes,
        n_select=1,
    )

**Comment by hmacdope** [comment]
Although thinking about this more this is a 1:Many comparison, not a 1:1 comparison, so you probably want to compute the ligand that has the minimum distance to all other ligands in MCS space, rather than just the best match for each ligand and do some aggregation. 

Something like: https://gist.github.com/jhjensen2/6450138cda3ab796a30850610843cfff will probably do the trick, and then some metric on the resulting graph?

**Comment by JenkeScheen** [comment]
thanks @hmacdope that's helpful. Thinking about this it's actually non-trivial because it's not strictly about chemical similarity to the reference, it's also about whether the found reference is a good fit MCS-wise, i.e. if there are ring systems to be grown the reference should ideally not contain a ring on that site.

**Comment by hmacdope** [comment]
Right, so this basically boils down to the "is this a good transformation" question.

**Comment by JenkeScheen** [comment]
actually this might be easier than I thought because we're not actually using the crystal reference pose for calculations, just for alignment. So if we take a reference pose that spans the space of R groups we should generally be able to pose our prospective compounds in a way that agrees with the reference pose. 

So a good strategy would probably be to take the largest compound in the prospective set and find its closest neighbor in the reference crystals

**Comment by hmacdope** [comment]
We ended up implementing this no @JenkeScheen? Closing, re-open if untrue.
