### ISSUE TITLE
`asap-ml` : train on all datasets across targets with reasonable quantity

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#929]
we need to start leveraging @kaminow 's ML models for production in project support with Ben's guidance. For this we should start building local models that are trained on ASAP data rather than moonshot data, as we already have for e.g. `SARS-CoV-2-Mac1`. We should also look at other endpoints beside potency (e.g. ADMET). Further model tweaks such as jittering and hyperparameter changes should be fed into this once Ben has made progress with this.

- [x] scope out which endpoints to predict on and which targets we can span
- [x] sketch out an automated architecture for training models 
- [x] build the architecture while making it routinely re-train once enough new data has appeared
- [x] hook up the training to `asap-hindsight` so that we can keep track of how well we're doing

**Comment by hmacdope** [comment]
Done with skynet
