### ISSUE TITLE
Expand functionality of MCSS-based selection of complexes

### ISSUE THREAD

**Issue by apayne97** [asapdiscovery/asapdiscovery#96]
## Description
**Problem**: We're using the MCSS to choose which complexes to use for docking. However, currently we have some specific design goals (i.e. expanding into the P3/P4 pocket), which may note be well captured by the MCSS. Namely, a complex with no P3-substituent will likely be a poor receptor model to choose from even if it has a high MCSS.

**Solution**: There are many ways to choose which complex to use. OpenEye has plenty of tools even within the MCSS object to enable more flexible selection of receptor complexes.

## TODO
- [ ] implement other MCSS algorithms

**Comment by hmacdope** [comment]
I am closing as out of scope for now
