### ISSUE TITLE
`ASAP-Alchemy`: BespokeFit

### ISSUE THREAD

**Issue by jthorton** [asapdiscovery/asapdiscovery#963]
To reach state-of-the-art performance we plan on integrating BespokeFit into ASAP-Alchemy. We will be following the interface with alchemiscale and assuming the server and workers are set up separately and Alchemy will handle submitting and collecting bespoke parameters from the server and using the force field in submissions to alchemiscale. 

## MVP
- `ASAP-Alchemy bespoke` subcommand which handles the interface to bespokefit.
- `ASAP-Alchemy bespoke submit` submit the planned network ligands to bespokefit using our predefined fitting workflow can optionally take a custom fitting workflow made with bespokefit.
- `ASAP-Alchemy bespoke status` view the status of a set of molecules submitted to bespokefit
- `ASAP-Alchemy bespoke gather` collects the final force field from all complete optimisations warns that some molecules might not be parameterised yet.

## Extra
- `ASAP-Alchemy bespoke seed` submit a set of experimental ligands from cdd or some other source to bespokefit to calculate transferable parameters which can be quickly used when needed at the next FEC request. This might not be needed if we make submit general enough to take many input types.

cc @JenkeScheen

**Comment by jthorton** [comment]
We also need to ensure that we trigger the deduplication of `Transformations` in alchemiscale as the forcefield grows over time. The deduplication is based on the hash of the `Transformation` object which contains all protocol settings so the growing full string of the forcefield will cause this to fail. One option which involves slightly more work is that we only include the specific parameters needed by the ligands in each edge rather than the entire forcefield. We would then need to store the bespoke parameters for each ligand when we run `ASAP-Alchemy bespoke gather` and make sure they are combined into the base forcefield in a consistent manner.

**Comment by hmacdope** [comment]
We also need to sort out auth for our deployed instance, A few options here, but I think the best will be a param to require an API token in the HTTP header, happy to help with this @jthorton

**Comment by hmacdope** [comment]
Issue raised at https://github.com/openforcefield/openff-bespokefit/issues/343

**Comment by jthorton** [comment]
With #1115 we now have an interface to bespokefit which is working in testing locally however installation is complicated due to pins on the openff-toolkit and we need a few new releases to help with this.
- [ ] new release of bespokefit with client once merged https://github.com/openforcefield/openff-bespokefit/pull/351
- [ ] new release of alchemiscale-client which works with gufe and openfe >1 
- [ ] new qcengine release with aimnet2 and mace interface

**Comment by hmacdope** [comment]
@jthorton do we have a branch on `BespokeFit` for `Traefik` reverse proxy integration?  I can help with that aspect also.

**Comment by hmacdope** [comment]
After some discussion with @jthorton we have decided just to pretrain a forcefield and then host it as an artefact, which will be simpler.
