### ISSUE TITLE
`alchemiscale 0.4` -> `asap-alchemy` QOL upgrades

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#985]
[based on a discussion with `Datryllic` and @jthorton ]

### 1. `status -a` table generation
No direct method of getting networks with actioned tasks. Could resolve this by geting individual network status counts with a `get_network_status()` call -> @dotsdl and @ianmkenney will open a PR.

### 2. `status -t` traceback retrieval
Potential solutions:
- ability to get a `get_network_failures()` method
- server-side traceback extraction for a collection of tasks within `alchemiscale`
- if `protocolDAG` fails -> pass the failure information to the StateStore

@dotsdl and @ianmkenney will formulate this in an issue on `alchemiscale` repo
### 3. `submit -pr` prioritization
keep `query_networks()`. that list of scoped keys, feed into `get_networks_status()` which will give us all the statuses. Then we can do the juggling of weights locally. There's also a `get_networks_weights()` which would take the same list of network keys (and `set_networks_weight()`).

**Comment by dotsdl** [comment]
@JenkeScheen are there outstanding items in this issue? If so, can you spin them out into their own issues so we can more easily action effort on them?

**Comment by JenkeScheen** [comment]
these are all resolved
